# -*- coding: utf-8 -*-
"""Customer Segmentation Task.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GRAZDidRmq0xXXyUbrcmI0xVi451FGj9
"""

import sys
import pandas as pd
import numpy as np
import matplotlib
import sklearn

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Matplotlib:", matplotlib.__version__)
print("Scikit-learn:", sklearn.__version__)

!pip install scikit-learn==1.9.0

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

df = pd.read_csv("Mall_Customers.csv")

df.head()

df.tail()

df.shape

df.info()

df.isnull().sum()

df.duplicated().sum()

df.describe()

df.columns

X = df[['Age','Annual Income (k$)','Spending Score (1-100)']]

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

wcss = []

for i in range(1,11):
    kmeans = KMeans(n_clusters=i, random_state=42)
    kmeans.fit(X_scaled)
    wcss.append(kmeans.inertia_)

plt.figure(figsize=(8,5))

plt.plot(range(1,11),wcss,marker='o')

plt.title("Elbow Method")

plt.xlabel("Number of Clusters")

plt.ylabel("WCSS")

plt.show()

kmeans = KMeans(n_clusters=5, random_state=42)

clusters = kmeans.fit_predict(X_scaled)

df["clusters"]=clusters

df.head()

df["clusters"].value_counts()

plt.figure(figsize=(8,6))

plt.scatter(
    df["Annual Income (k$)"],
    df["Spending Score (1-100)"],
    c=df["clusters"]
)

plt.xlabel("Annual Income")
plt.ylabel("Spending Score")
plt.title("Customer Segmentation")

plt.show()

df.groupby("clusters")[["Age","Annual Income (k$)","Spending Score (1-100)"]].mean()

kmeans.cluster_centers_

centers = scaler.inverse_transform(kmeans.cluster_centers_)

centers

df.to_csv("Clustered_Customers.csv", index=False)

from google.colab import files

files.download("Clustered_Customers.csv")

"""Cluster Interpretation
Cluster 0
Average Age: 55.28 years
Annual Income: 47.62 k$
Spending Score: 41.71
Interpretation: Older customers with medium income and moderate spending behavior.
Cluster 1
Average Age: 32.88 years
Annual Income: 86.10 k$
Spending Score: 81.53
Interpretation: Young customers with high income and high spending score. These are premium and high-value customers.
Cluster 2
Average Age: 25.77 years
Annual Income: 26.12 k$
Spending Score: 74.85
Interpretation: Young customers with low income but high spending score. They are active shoppers despite lower income.
Cluster 3
Average Age: 26.73 years
Annual Income: 54.31 k$
Spending Score: 40.91
Interpretation: Young customers with average income and average spending score. These are regular customers.
Cluster 4
Average Age: 44.39 years
Annual Income: 89.77 k$
Spending Score: 18.48
Interpretation: Middle-aged customers with high income but low spending score. They have high purchasing power but spend less.
"""